"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SecondaryInfoController = exports.MailController = exports.UserController = exports.ManufacturerController = exports.FilterController = exports.AttributeController = exports.ProductController = exports.CategoryController = void 0;
exports.CategoryController = require("./controllers/category/CategoryController");
exports.ProductController = require("./controllers/product/ProductController");
exports.AttributeController = require("./controllers/attribute/AttributeController");
exports.FilterController = require("./controllers/filter/FilterController");
exports.ManufacturerController = require("./controllers/manufacturer/ManufacturerController");
exports.UserController = require("./controllers/user/UserController");
exports.MailController = require("./controllers/mail/MailController");
exports.SecondaryInfoController = require("./controllers/secondaryInfo/SecondaryInfoController");
